CREATE DATABASE F1;
USE F1;

CREATE TABLE DRIVERS (
DRIVER_NAME VARCHAR (40),
SURNAME VARCHAR (40) primary key,
TEAM VARCHAR (40),	
COUNTRY VARCHAR (40),
PODIUMS INT,
POINTS FLOAT,
GRANDS_PRIX_ENTERED INT,
WORLD_CHAMPIONSHIPS INT,
HIGHEST_RACE_FINISH INT,
HIGUEST_GRID_POSITION INT,
DATE_BIRTH VARCHAR(15),
PLACE_BIRTH VARCHAR(40),
FOREIGN KEY (TEAM) REFERENCES TEAMS (TEAM_NAME)
);	


CREATE TABLE TEAMS (
TEAM_NAME VARCHAR(40) primary key,
BASE VARCHAR(40),
TEAM_CHIEF VARCHAR(40),
TECHNICAL_CHIEF VARCHAR(40),
CHASSIS VARCHAR(40),
POWER_UNIT VARCHAR(40),
FIRST_ENTRY INT,
WORLD_CHAMPIONSHIPS INT,
HIGHEST_RACE_FINISH INT,
POLE INT,
FASTEST_LAPS INT
);	


CREATE TABLE RACE_RESULTS (
RACEID VARCHAR(40) primary key,
DRIVER_SURNAME VARCHAR (40),
TEAM_NAME VARCHAR(40),
POS INT,
LAPS INT,
TIME_RETIRES TIME,
PTS INT,
FOREIGN KEY (DRIVER_SURNAME) REFERENCES DRIVERS (SURNAME),
FOREIGN KEY (TEAM_NAME) REFERENCES TEAMS (TEAM_NAME)
);


CREATE TABLE FASTEST_LAPS (
RACEID VARCHAR(40) primary key,
DRIVER_SURNAME VARCHAR (40),
TEAM_NAME VARCHAR (40),
POS INT,
DRIVER_TEAM VARCHAR (40),
LAP INT, 
TIME_OF_DAY TIME, 
LAP_TIME TIME,
AVG_SPEED FLOAT,
FOREIGN KEY (DRIVER_SURNAME) REFERENCES DRIVERS (SURNAME),
FOREIGN KEY (RACEID) REFERENCES RACE_RESULTS (RACEID),
FOREIGN KEY (TEAM_NAME) REFERENCES TEAMS (TEAM_NAME)
);


CREATE TABLE QUALIFYING (
RACEID VARCHAR(40) primary key,
DRIVER_SURNAME VARCHAR (40),
TEAM_NAME VARCHAR (40),
POS INT,
Q1 TIME, 
Q2 TIME,
Q3 TIME,
LAPS INT,
FOREIGN KEY (DRIVER_SURNAME) REFERENCES DRIVERS (SURNAME),
FOREIGN KEY (RACEID) REFERENCES RACE_RESULTS (RACEID),
FOREIGN KEY (TEAM_NAME) REFERENCES TEAMS (TEAM_NAME)
);



CREATE TABLE DHL_FAST_LAP_AWARD (
RACEID VARCHAR(40) primary key,
DRIVER_SURNAME VARCHAR (40),
TEAM_NAME VARCHAR (40),
AWARD_TIME float,
FOREIGN KEY (RACEID) REFERENCES RACE_RESULTS (RACEID),
FOREIGN KEY (DRIVER_SURNAME) REFERENCES DRIVERS (SURNAME),
FOREIGN KEY (TEAM_NAME) REFERENCES TEAMS (TEAM_NAME)
);


























